# Generated by Django 3.2.12 on 2022-04-02 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_auto_20220328_2019'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='image',
            field=models.ImageField(null=True, upload_to='articles'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
